### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by Oudwins** [indaco/teseo#1]
Hey! Would you mind making a release? I have added the project to awesome-templ (https://github.com/templ-go/awesome-templ/) even though it doesn't 100% meet the criteria because I have used it quite a bit and its very nice!

For github actions to make relases as well as tests you can check this repo -> https://github.com/Oudwins/zog

Thanks!

**Comment by Oudwins** [comment]
I just remembered, I said I would suggest some feedback. I haven't used the package lots and so far it has been exactly what I needed. The only idea I had that would be nice is to have a little bit of go style comments documenting some of the properties. Mostly so lazy people like me don't have to go and check online when they don't remember what a property does

**Comment by indaco** [comment]
Hey, first thanks for listing `teseo` in awesome-templ repos.

Yes, I will create a release tag for it.

Related to your suggestion "_go style comments documenting some of the properties_" I am not so sure but will think on it.

 What do you think on an intermediate solution? I mean, links in go comments to the entity doc pages?

e.g. In the go comments for the [Action](https://pkg.go.dev/github.com/indaco/teseo@v0.0.0-20240910113229-319a463f0385/schemaorg#Action) type, rather than "Action represents a Schema.org Action object " I do something like "Action represents a Schema.org [Action](https://schema.org/Action) object"?

**Comment by indaco** [comment]
@Oudwins I just released [v0.1.0](https://github.com/indaco/teseo/releases/tag/v0.1.0)

I added link to each entity page on the go comments. e.g. https://github.com/indaco/teseo/blob/dc9979219640e8f401e7d3064b54a742584fd6c3/schemaorg/article.go#L14
